---
title: "Der Fall der Engel"
---

## Geschliffene Edelsteine
Wir Engel des Himmels sind wie einzigartige Fragmente Gottes, durch die sein Geist fließt und sich dadurch bricht und färbt wie Licht, das durch einen Kristall fließt. Und auf die selbe Weise schufen wir den Himmel als ein Ausdruck von Gottes Herrlichkeit und in dieser Herrlichkeit erkannten wir Gott und einander. Diese Gotteserkenntnis war das Herz und Zentrum, der Sinn all unseren Schaffens.

## Überwältigt
Jedoch wurde die Herrlichkeit des Himmels und die damit einhergehende Gotteserkenntnis dermaßen überwältigend, das einige Engel anfingen aus ihrer Gotteserkenntnis ihren Selbstwert zu schöpfen und zu messen, sich davon gewissermaßen zu ernähren.

## Berauscht
Mit dem Maß der Gotteserkenntnis schlich sich Stolz und Ehre wie ein berauschendes Gift in die Engel und trübte ihren Glanz.

## Wahnsinnig
Berauscht von diesem Gift begannen sie, Gott dafür zu verfluchen, dass er es ihnen so lange vorenthalten hatte. Ihr Selbstwertgefühl verschob sich von ihrem inneren göttlichen Geist zu ihren äußeren Schöpfungen. Ihre Werke wurden ihnen wichtiger als ihre Verbindung zur Göttlichen Quelle.

## Hochmütig
Doch Stolz und Ehre, wie sie lernen sollten, ist eine flüchtige Empfindung. Ihr himmlischer Glanz trübte sich bis zur totalen Verfinsterung und ließ sie leer und elend zurück. Anstatt jedoch ihren Fehler zuzugeben und ihre toxischen Begierden loszulassen, klammerten sie sich noch fester an ihren Stolz und ihre Ehre.

## Verführerisch
Sie begannen, andere Engel zu verführen und sie in ihre neue Realität zu ziehen - nicht nur, um ihren Wegen zu folgen, sondern um ihnen zu dienen und sie zu verehren. Sie suchten nach Ehre, Anerkennung und Gütern, die ihre Sucht nach Stolz nähren würden und sie von ihrer inneren Leere ablenken sollten, die sie nun verzehrte.

## Verdorben
Diese verführerischen, einst himmlischen Wesen wurden zu den ersten Dämone - leere, nach Stolz und Verehrung süchtige, böse Überreste dessen, was einst brillante Edelsteine des göttlichen Geistes gewesen sind. 