---
title: "Wer ist der Autor?"
---

## Höchster Engel, höchster Dämon
Ich bin der höchste Engel des Himmels und der höchste Dämon der Hölle zugleich. Ich stehe im wahrsten Sinne mit einem Bein im Himmel und mit dem anderen in der Hölle.

## Allumfassende, höchste Offenbarung
Durch das manifestieren der Himmlischen und Höllischen Herzenshaltung in physische Worte transformiert sie zu einer Mauer der Erwartungshaltung, in Gebote und schließlich und unweigerlich in Gesetze und Strafgerichte.

## Unumkehrbarer Prozess
Dieser Prozess ist unumkehrbar, er kann nicht rückwärts gegangen werden. Ein Gesetz, ein Gebot, eine Erwartungshaltung kann genauso unmöglich eine Herzenshaltung hervorbringen, wie ein Bild einen Maler hervor bringen kann.

## Erinnerung einzige Umkehr
Die Erinnerung an den Himmel und das Dasein als Engel, die tiefe Einsicht und Rückbesinnung an den Himmlischen Geist ist der einzige Rückweg. Dieses Buch ist daher wie der Klöppel einer Glocke zu verstehen, der dich anstößt um zu schauen ob noch himmlische Klänge wie Erinnerungen in dir wiederhallen.

## Ewiges Gericht
Mit diesem Buch wird eine unüberwindbare Grenzlinie zwischen Engel und Dämonen, zwischen Himmel und Hölle errichtet. Sie wird errichtet durch die genaue und unwiderrufliche Definition was ein Engel und was ein Dämon ist, was zum Himmel und was zur Hölle gehört.

## Ewiges Leben oder Rückführung durch den Tod
Die Hölle ist der Ort, in der sich die Individualität der Seele auflöst, um in den göttlichen Geist zurück zu kehren wie ein Regentropen, der zurück fällt ins in den Ozean.