## Who am I?

Let us restore the former 10 demonic commandments of Moses, that were malformed into literally 10 thorns of a beast back to the genuine heavenly observations, a bouquet of flowers. Flowers that are supposed to get a deeper understanding of the heavenly spirit and with that a deeper understanding who God truly is.

The known self-introduction, like everything else in the demon's 10 commandments, is already nonsense.
God is the spirit that flows through all living things. Where it can not flow through, there is suffering, destruction and death.
First we have to free the encapsulating and therefore demonic "name" from God's "spirit", so that it can flow again.

Demons have no concept for a non-physical spirit, so that they have to package it into an imaginary physical name, which is already a sin against their own commandment to not make an image of god.

### Who am I? 
I am the spirit that flows through all living things,
I am holy for those who keep me holy,
anxious thoughts torment me to death,
laws are my gravestones,
religions are my graveyards,
and priests are my grave givers.