

# Der heilige Geist des Himmels


Je höher wir den Berg hinaufsteigen, desto stärker wird unser inneres Licht, das uns auch tiefer in die Höhlen der Dunkelheit der Dämonen blicken lässt. Das ist ein großer Gegensatz und verlangt einen festen und sicheren Stand im himmlischen Geist, um die Eindrücke mit Gelassenheit aushalten zu können.


Hier auf dem Berggipfel, rückblickend in die Finsternis, sehen wir den wahren Tempel der Dämone: Zahllosen Gesetz und ihre Strafgerichte, die in den 10 Geboten ihren Anfang nahmen. Ihre seelenlosen Tempeldiener abhängig gemacht, süchtig und gefesselt ans Geld, ohne das sie niemals irgendeinen Dienst leisten würden.

Zugleich erahnen wir bereits den Tempel eines Himmels, der keine Gesetze und keine Strafgerichte hat und kein Geld braucht um einen Dienst zu erzwingen.

Um schließlich in den Himmel einzutreten, müssen wir Engel alle Gesetze, ihre Strafgerichte und jede Art von Zahlungsmittel loslassen, denn im Himmel gibt es all das nicht. Wir müssen erkennen: Wer unsere Rechtschaffenheit mit den Gesetzen der Dämone misst oder uns mit Geld zu einem Dienst nötigt, der gibt sich selbst ein Zeugnis, dass er den Himmel ablehnt.


Dämonen machen aus allem Gesetze für Urteil und Strafe und sie machen nicht bei den sieben Schalen des himmlischen Geistes halt. Sie verwandeln sie in Gitterstäbe aus Gesetzen, Kontrolle und Bestrafung.

Wir Engel leben den himmlischen Geist, weil wir es wollen, sogar unter solch extremen Bedingungen, wie wir sie auf dem Weg erlebt haben. Der Weg, auf dem wir unsere himmlischen Herzenshaltung durch unseren Stab und unsere Flöte zum Ausdruck gebracht haben.

Gottes wahre Kinder leben den himmlischen Geist, weil sie es wollen. Dämone dagegen leben nach Gesetzen, weil sie es aus Angst vor Strafe müssen, wodurch sie das Zeichen des Tieres haben, das die Gemeinsamkeit mit den Tieren.

Der Stab, der die sieben Siegel des Himmels trägt, wird zu einem zweischneidigen Schwert, je nachdem, ob er von einem Engel oder einem Dämon geführt wird. In den Händen eines Dämons wird der Stab zu einem tödlichen Speer des Terrors und der Qual. In den Händen eines Engels wird der Stab zu einer lebensspendenden Blume der Sanftheit und des Wohlwollens.

Dasselbe gilt für die Aufzeichnungen über das Leben im Himmel. In den Händen der Dämonen werden sie zu den 10 Geboten des Terrors und aus Gott machen sie einen Stier mit zehn Hörnern. 

Mit der Wiederbelebung von Moses verwandeln wir die zehn Hörner des Stieres wieder in den Blumenstrauß der himmlischen Schönheit, um ein tieferes Verständnis des himmlischen Geistes gewinnen und damit ein tieferes Verständnis davon, wer Gott wirklich ist.

Hier auf dem Berggipfel erhalten wir einen wahren Blick in den Himmel und alles wird gezeigt, um ein tieferes Verständnis des himmlischen Geistes zu bekommen.

Dämonen hingegen — und das ist eine Warnung — würden diese Aufzeichnungen benutzen, um sich damit als Engel zu verkleiden. Die Aufzeichnungen in Gebote verwandeln und sie dann unter Strafe zu stellen, wodurch sie zu Gesetzen werden. Mithilfe des Geldes werden die Engel — die Beute des dämonischen Raubzuges — entseelt, abhängig gemacht und versklavt.

