---
title: "Neuntes Gebot"
---

# Du sollst nicht lügen

Hier sprach Jesus abermals: "Der Splitter, den du in den Augen eines anderen siehst, ist immer ein Fragment der Balken, die du in deinen eigenen Augen hast."

Während die Stärke der gefallenen Geister auf ihrer Macht basiert, gründet sich unsere engelhafte Stärke auf unsere Sanftmut. Der himmlische Geist der Engel ist so gütig und sanft, voller Mitgefühl und stets um Verständnis bemüht und daher vertrauenswürdig. Niemand muss Furcht haben, die Wahrheit zu sagen, daher gibt es keine Lügen im Himmel.

Die Dämonen jedoch bekämpfen Lügen auf die entgegengesetzte Weise: mit Gekränktheit bis hin zur Wut und mit der Macht der Gesetze und der Drohung der Bestrafung. Wir Engel jedoch wissen, dass das Gekränktsein oder gar Wut die Drehpunkt ist, um die Schuld auf die andere Seite zu wenden, so dass man niemals einen Engel gekränkt oder gar wütend sehen wird.

Wenn uns also jemand mit einer Lüge geschlagen hat, schlagen wir uns selbst nochmals mit der Frage, wie wir so weit vom himmlischen Geist abfallen konnten, dass wir unsere Vertrauenswürdigkeit verloren haben.

Wie kristallklare Bergquellen sprudelt die Wahrheit natürlich aus engelshaften Herzen hervor. Wir brauchen keine Gesetze gegen die Lüge, denn wo Liebe und Vertrauen herrschen, da blüht die Wahrheit wie Blumen im Frühling. Unsere Wahrhaftigkeit ist nicht aus Furcht vor Strafe geboren, sondern aus der reinen Freude an der Klarheit des göttlichen Lichts, das durch uns strahlt.