project:
  type: book
  output-dir: Das-Herz-von-Jerusalem
book:
  title: "Das Herz von Jerusalem"
  language: de
  chapters:
    - index.qmd
    - part: "Vorwort"
      chapters:
      - de/book-about-1.qmd
      - de/book-about-2.qmd
      - de/book-about-3.qmd
#      - de/book-about-4.qmd
#      - de/book-about-5.qmd
    - part: "Engel, erinnert euch!"
      chapters:
      - de/book-preface-1.qmd
      - de/book-preface-2.qmd
      - de/book-preface-3.qmd
#      - de/book-preface-4.qmd
    - part: "Jesus Auferstehung"
      chapters:
      - de/chapter-1-preface-1.qmd
      - de/chapter-1-1.qmd
      - de/chapter-1-2.qmd
      - de/chapter-1-3.qmd
      - de/chapter-1-4.qmd
      - de/chapter-1-5.qmd
      - de/chapter-1-6.qmd
      - de/chapter-1-7.qmd
      - de/chapter-1-epilogue-1.qmd
    - part: "Moses Auferstehung"
      chapters:
#      - de/chapter-2-preface-1.qmd
      - de/chapter-2-preface-2.qmd
      - de/chapter-2-preface-3.qmd
      - de/chapter-2-preface-4.qmd
      - de/chapter-2-1.qmd
      - de/chapter-2-2.qmd
      - de/chapter-2-3.qmd
      - de/chapter-2-4.qmd
      - de/chapter-2-5.qmd
      - de/chapter-2-6.qmd
      - de/chapter-2-7.qmd
      - de/chapter-2-8.qmd
      - de/chapter-2-9.qmd
      - de/chapter-2-10.qmd
      - de/chapter-2-epilogue-1.qmd
    - part: "Jerusalems Auferstehung"
      chapters:
      - de/chapter-3-preface-1.qmd
      - de/chapter-3-preface-2.qmd
      - de/chapter-3-preface-3.qmd
      - de/chapter-3-preface-4.qmd
      - de/chapter-3-preface-5.qmd
      - de/chapter-3-preface-6.qmd
      - de/chapter-3-preface-7.qmd
      - de/chapter-3-1.qmd
      - de/chapter-3-2.qmd
      - de/chapter-3-3.qmd
      - de/chapter-3-4.qmd
      - de/chapter-3-5.qmd
      - de/chapter-3-6.qmd
      - de/chapter-3-7.qmd
      - de/chapter-3-epilogue-1.qmd
#    - part: de/book-epilogue-index.qmd
#      chapters:
#      - de/book-epilogue-1.qmd
#      - de/book-epilogue-2.qmd
#      - de/book-epilogue-3.qmd
#      - de/book-epilogue-4.qmd
#      - de/book-epilogue-5.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    code-fold: false
  
  pdf:
    documentclass: book
    toc: true
    number-sections: false
    code-fold: false

  epub:
    cover-image: de/images/blossom-crown.png
    title-page: true
    toc: true
    number-sections: false
    code-fold: false

  docx:
    toc: true
    number-sections: false
    code-fold: false    